[theme]
primaryColor="#4CAF50"                # A calming green associated with health and wellness
backgroundColor="#FFFFFF"             # Clean, white background for clarity
textColor="#212121"                   # Dark color for excellent contrast
secondaryBackgroundColor="#F5F5F5"   # Light grey for secondary backgrounds
font="sans serif"                     # Readable sans-serif font
